version: '3'
services:
  app:
    build:
      context: ./.docker/app/
      args:
        OPENCART_VERSION: ${OPENCART_VERSION}
    env_file:
      - ./.env/.app
      - ./.env/.db
    volumes:
      -  appdata:/var/www/html
      ## Host mounts with performance penalty, only put what is necessary here
      # - ./application:/var/www/html
      # - ./extension:/var/www/html/extension
      ## Support for SSL
      - ssldata:/etc/nginx/certs
    depends_on:
      - db
  server:
    build: ./.docker/server/
    volumes_from:
      - app
    ports:
      - "80:80"
      - "443:443"
    links:
      - db
      - app
  db:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - ./.env/.db
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"
  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - db
volumes:
  db-data:
  appdata:
  ssldata:
